
app:
  name: "MineSweeper Server"
  version: "1.0.0"
server:
  port: 8080
  host: "localhost"
mine:
  width: 30
  height: 16
  mines: 99
database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "mines"
smtp:
  smtpServer: "smtp.gmail.com"
  email: "smtp.gmail.com"
  password: 587
