# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get version
        id: get_version
        shell: bash
        run: |
          echo "version=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.5
        with:
          version: 11

      - name: Set node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: pnpm
          cache-dependency-path: mines-client/pnpm-lock.yaml

      - name: install-deps
        run: cd mines-client && pnpm install

      - name: build-client
        run: cd mines-client && pnpm run build

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.3"

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o output/mines-linux-amd64
          GOOS=windows GOARCH=amd64 go build -o output/mines-windows-amd64.exe
          GOOS=darwin GOARCH=arm64 go build -o output/mines-darwin-arm64

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mines
          path: output/

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            output/mines-linux-amd64
            output/mines-windows-amd64.exe
            output/mines-darwin-arm64
          name: "Mines ${{ env.version }}"
